name: appdeteccion
description: "App de fotodeteccion vehicular con IA"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Iconos y Estilo
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  intl: ^0.19.0

  # Comunicación y Red
  http: ^1.2.0

  # Mapas y GPS
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  geolocator: ^11.0.0
  geocoding: ^3.0.0

  # Cámara e IA
  camera: ^0.10.5
  google_mlkit_text_recognition: ^0.11.0 
  flutter_vision: ^1.1.4 
  image: ^4.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/best_int8.tflite
    - assets/labels.txt
    - assets/Logo Yo Amo Cocha Oficial 1.png