services:
  backend:
    build:
      context: ./backend
    container_name: lpr-backend-api
    restart: always
    ports:
      - "8009:8009"
    env_file:
      - .env.dev
    networks:
      - lpr-network

networks:
  lpr-network:
    driver: bridge